Import chromium-66.0.3359.117.tar.xz from Google

diff --git a/third_party/depot_tools/autoninja b/third_party/depot_tools/autoninja
--- a/third_party/depot_tools/autoninja
+++ b/third_party/depot_tools/autoninja
@@ -9,4 +9,14 @@
 # Also print it to reassure that the right settings are being used.
 command=$(python $(dirname -- "$0")/autoninja.py "$@")
 echo $command
-exec $command
+$command
+if [ $? -eq 0 ]; then
+  if [ "$NINJA_SUMMARIZE_BUILD" == "1" ]; then
+    python $(dirname -- "$0")/post_build_ninja_summary.py $@
+  fi
+  exit
+fi
+# Return an error code of 1 so that if a developer types:
+# "autoninja chrome && chrome" then chrome won't run if the build fails.
+exit 1
+
