Import chromium-browser_50.0.2661.102.orig.tar.xz from Ubuntu Yakkety
All .gitignore files dropped, as this would have prevented much of the
tarball being imported.
 # find . -name .gitignore -delete

Removed files over 50MB in size to make GitHub happy.
 # find . -type f -size +49M -delete

diff --git a/build/android/adb_gdb b/build/android/adb_gdb
--- a/build/android/adb_gdb
+++ b/build/android/adb_gdb
@@ -15,13 +15,11 @@
 PROGNAME=$(basename "$0")
 PROGDIR=$(dirname "$0")
 
+# Force locale to C to allow recognizing output from subprocesses.
+LC_ALL=C
+
 # Location of Chromium-top-level sources.
 CHROMIUM_SRC=$(cd "$PROGDIR"/../.. >/dev/null && pwd 2>/dev/null)
-
-# Location of Chromium out/ directory.
-if [ -z "$CHROMIUM_OUT_DIR" ]; then
-  CHROMIUM_OUT_DIR=out
-fi
 
 TMPDIR=
 GDBSERVER_PIDFILE=
@@ -86,8 +84,6 @@ PROGNAME=${ADB_GDB_PROGNAME:-$(basename "$0")}
 ACTIVITY=$DEFAULT_ACTIVITY
 ADB=
 ANNOTATE=
-# Note: Ignore BUILDTYPE variable, because the Ninja build doesn't use it.
-BUILDTYPE=
 FORCE=
 GDBEXEPOSTFIX=gdb
 GDBINIT=
@@ -106,6 +102,7 @@ PULL_LIBS_DIR=
 SANDBOXED=
 SANDBOXED_INDEX=
 START=
+ATTACH_DELAY=1
 SU_PREFIX=
 SYMBOL_DIR=
 TARGET_ARCH=
@@ -180,14 +177,17 @@ for opt; do
     --start)
       START=true
       ;;
+    --attach-delay=*)
+      ATTACH_DELAY=$optarg
+      ;;
     --su-prefix=*)
       SU_PREFIX=$optarg
       ;;
     --symbol-dir=*)
       SYMBOL_DIR=$optarg
       ;;
-    --out-dir=*)
-      CHROMIUM_OUT_DIR=$optarg
+    --output-directory=*)
+      CHROMIUM_OUTPUT_DIR=$optarg
       ;;
     --target-arch=*)
       TARGET_ARCH=$optarg
@@ -201,14 +201,8 @@ for opt; do
     --verbose)
       VERBOSE=$(( $VERBOSE + 1 ))
       ;;
-    --debug)
-      BUILDTYPE=Debug
-      ;;
-    --release)
-      BUILDTYPE=Release
-      ;;
     -*)
-      panic "Unknown option $OPT, see --help." >&2
+      panic "Unknown option $opt, see --help." >&2
       ;;
     *)
       if [ "$PACKAGE_NAME" ]; then
@@ -219,11 +213,6 @@ for opt; do
       ;;
   esac
 done
-
-print_help_options () {
-  cat <<EOF
-EOF
-}
 
 if [ "$HELP" ]; then
   if [ "$ADB_GDB_PROGNAME" ]; then
@@ -266,16 +255,12 @@ directory.
 The script tries to find the most recent version of the debug version of
 shared libraries under one of the following directories:
 
-  \$CHROMIUM_SRC/<out>/Release/lib/           (used by Ninja builds)
-  \$CHROMIUM_SRC/<out>/Debug/lib/             (used by Ninja builds)
-  \$CHROMIUM_SRC/<out>/Release/lib.target/    (used by Make builds)
-  \$CHROMIUM_SRC/<out>/Debug/lib.target/      (used by Make builds)
+  \$CHROMIUM_SRC/<out>/lib/                (used by GYP builds)
+  \$CHROMIUM_SRC/<out>/lib.unstripped/     (used by GN builds)
 
-Where <out> is 'out' by default, unless the --out=<name> option is used or
-the CHROMIUM_OUT_DIR environment variable is defined.
+Where <out> is determined by CHROMIUM_OUTPUT_DIR, or --output-directory.
 
-You can restrict this search by using --release or --debug to specify the
-build type, or simply use --symbol-dir=<path> to specify the file manually.
+You can set the path manually via --symbol-dir.
 
 The script tries to extract the target architecture from your target device,
 but if this fails, will default to 'arm'. Use --target-arch=<name> to force
@@ -316,7 +301,7 @@ Valid options:
   --sandboxed           Debug first sandboxed process we find.
   --sandboxed=<num>     Debug specific sandboxed process.
   --symbol-dir=<path>   Specify directory with symbol shared libraries.
-  --out-dir=<path>      Specify the out directory.
+  --output-directory=<path> Specify the output directory (e.g. "out/Debug").
   --package-name=<name> Specify package name (alternative to 1st argument).
   --privileged          Debug first privileged process we find.
   --privileged=<num>    Debug specific privileged process.
@@ -324,6 +309,9 @@ Valid options:
   --pid=<pid>           Specify application process pid.
   --force               Kill any previous debugging session, if any.
   --start               Start package's activity on device.
+  --attach-delay=<num>  Seconds to wait for gdbserver to attach to the
+                        remote process before starting gdb. Default 1.
+                        <num> may be a float if your sleep(1) supports it.
   --ui                  Use gdbtui instead of gdb
   --activity=<name>     Activity name for --start [$DEFAULT_ACTIVITY].
   --annotate=<num>      Enable gdb annotation.
@@ -344,15 +332,24 @@ Valid options:
   --no-pull-libs        Do not extract any system library.
   --libs-dir=<path>     Specify system libraries extraction directory.
 
-  --debug               Use libraries under out/Debug.
-  --release             Use libraries under out/Release.
-
 EOF
   exit 0
 fi
 
 if [ -z "$PACKAGE_NAME" ]; then
   panic "Please specify a package name on the command line. See --help."
+fi
+
+if [[ -z "$CHROMIUM_OUTPUT_DIR" ]]; then
+  if [[ -e "build.ninja" ]]; then
+    CHROMIUM_OUTPUT_DIR=$PWD
+  else
+    panic "Please specify an output directory by using one of:
+       --output-directory=out/Debug
+       CHROMIUM_OUTPUT_DIR=out/Debug
+       Setting working directory to an output directory.
+       See --help."
+   fi
 fi
 
 if [ -z "$NDK_DIR" ]; then
@@ -700,57 +697,30 @@ get_file_timestamp () {
 
 # Detect the build type and symbol directory. This is done by finding
 # the most recent sub-directory containing debug shared libraries under
-# $CHROMIUM_SRC/$CHROMIUM_OUT_DIR/
+# $CHROMIUM_OUTPUT_DIR.
 #
-# $1: $BUILDTYPE value, can be empty
 # Out: nothing, but this sets SYMBOL_DIR
 #
 detect_symbol_dir () {
-  local SUBDIRS SUBDIR LIST DIR DIR_LIBS TSTAMP
-  # Make places them under out/$BUILDTYPE/lib.target.
-  # GYP places debug libraries under out/$BUILDTYPE/lib
-  # GN places them under out/$BUILDTYPE/lib.unstripped
-  if [ "$1" ]; then
-    SUBDIRS="$1/lib $1/lib.target $1/lib.unstripped"
-  else
-    SUBDIRS="Release/lib Debug/lib Release/lib.target Debug/lib.target"
-    SUBDIRS+=" Release/lib.unstripped Debug/lib.unstripped"
+  # GYP places unstripped libraries under out/lib
+  # GN places them under out/lib.unstripped
+  local PARENT_DIR="$CHROMIUM_OUTPUT_DIR"
+  if [[ ! -e "$PARENT_DIR" ]]; then
+    PARENT_DIR="$CHROMIUM_SRC/$PARENT_DIR"
   fi
-  LIST=$TMPDIR/scan-subdirs-$$.txt
-  printf "" > "$LIST"
-  for SUBDIR in $SUBDIRS; do
-    DIR=$CHROMIUM_SRC/$CHROMIUM_OUT_DIR/$SUBDIR
-    if [ -d "$DIR" ]; then
-      # Ignore build directories that don't contain symbol versions
-      # of the shared libraries.
-      DIR_LIBS=$(ls "$DIR"/lib*.so 2>/dev/null)
-      if [ -z "$DIR_LIBS" ]; then
-        echo "No shared libs: $DIR"
-        continue
-      fi
-      TSTAMP=$(get_file_timestamp "$DIR")
-      printf "%s %s\n" "$TSTAMP" "$SUBDIR" >> "$LIST"
-    fi
-  done
-  SUBDIR=$(cat $LIST | sort -r | head -1 | cut -d" " -f2)
-  rm -f "$LIST"
-
-  if [ -z "$SUBDIR" ]; then
-    if [ -z "$1" ]; then
-      panic "Could not find any build directory under \
-$CHROMIUM_SRC/$CHROMIUM_OUT_DIR. Please build the program first!"
-    else
-      panic "Could not find any $1 directory under \
-$CHROMIUM_SRC/$CHROMIUM_OUT_DIR. Check your build type!"
+  SYMBOL_DIR="$PARENT_DIR/lib.unstripped"
+  if [[ -z "$(ls "$SYMBOL_DIR"/lib*.so 2>/dev/null)" ]]; then
+    SYMBOL_DIR="$PARENT_DIR/lib"
+    if [[ -z "$(ls "$SYMBOL_DIR"/lib*.so 2>/dev/null)" ]]; then
+      panic "Could not find any symbols under \
+$PARENT_DIR/lib{.unstripped}. Please build the program first!"
     fi
   fi
-
-  SYMBOL_DIR=$CHROMIUM_SRC/$CHROMIUM_OUT_DIR/$SUBDIR
   log "Auto-config: --symbol-dir=$SYMBOL_DIR"
 }
 
 if [ -z "$SYMBOL_DIR" ]; then
-  detect_symbol_dir "$BUILDTYPE"
+  detect_symbol_dir
 fi
 
 # Allow several concurrent debugging sessions
@@ -949,10 +919,16 @@ TARGET_PORT=$PORT
 
 # Select correct app_process for architecture.
 case $TARGET_ARCH in
-      arm|x86|mips) GDBEXEC=app_process;;
+      arm|x86|mips) GDBEXEC=app_process32;;
       arm64|x86_64) GDBEXEC=app_process64;;
       *) fail_panic "Unknown app_process for architecture!";;
 esac
+
+# Default to app_process if bit-width specific process isn't found.
+adb_shell ls /system/bin/$GDBEXEC
+if [ $? != 0 ]; then
+    GDBEXEC=app_process
+fi
 
 # Detect AddressSanitizer setup on the device. In that case app_process is a
 # script, and the real executable is app_process.real.
@@ -983,20 +959,21 @@ host:localhost:$HOST_PORT to device:localhost:$TARGET_PORT!"
 log "Starting gdbserver in the background:"
 GDBSERVER_LOG=$TMPDIR/gdbserver-$TMP_ID.log
 log "adb shell $COMMAND_PREFIX $TARGET_GDBSERVER :$TARGET_PORT \
---attach $PID $COMMAND_SUFFIX"
-("$ADB" shell $COMMAND_PREFIX $TARGET_GDBSERVER :$TARGET_PORT \
- --attach $PID $COMMAND_SUFFIX > $GDBSERVER_LOG 2>&1) &
+  --attach $PID $COMMAND_SUFFIX"
+"$ADB" shell $COMMAND_PREFIX $TARGET_GDBSERVER :$TARGET_PORT \
+  --attach $PID $COMMAND_SUFFIX > $GDBSERVER_LOG 2>&1 &
 GDBSERVER_PID=$!
 echo "$GDBSERVER_PID" > $GDBSERVER_PIDFILE
 log "background job pid: $GDBSERVER_PID"
 
-# Check that it is still running after a few seconds. If not, this means we
-# could not properly attach to it
-sleep 2
+# Sleep to allow gdbserver to attach to the remote process and be
+# ready to connect to.
+log "Sleeping ${ATTACH_DELAY}s to allow gdbserver to attach."
+sleep "$ATTACH_DELAY"
 log "Job control: $(jobs -l)"
 STATE=$(jobs -l | awk '$2 == "'$GDBSERVER_PID'" { print $3; }')
 if [ "$STATE" != "Running" ]; then
-  echo "ERROR: GDBServer could not attach to PID $PID!"
+  echo "ERROR: GDBServer either failed to run or attach to PID $PID!"
   if [ $(adb_shell su -c getenforce) != "Permissive" ];  then
     echo "Device mode is Enforcing. Changing Device mode to Permissive "
     $(adb_shell su -c setenforce 0)
