Import chromium-browser_45.0.2454.85.orig.tar.xz from Ubuntu Vivid
All .gitignore files dropped, as this would have prevented much of the
tarball being imported.
 # find . -name .gitignore -delete

Removed files over 50mb in size to make github happy.
 # find . -type f -size +49M -delete

diff --git a/build/android/adb_gdb b/build/android/adb_gdb
--- a/build/android/adb_gdb
+++ b/build/android/adb_gdb
@@ -26,6 +26,7 @@ fi
 TMPDIR=
 GDBSERVER_PIDFILE=
 TARGET_GDBSERVER=
+COMMAND_PREFIX=
 
 clean_exit () {
   if [ "$TMPDIR" ]; then
@@ -36,7 +37,7 @@ clean_exit () {
     fi
     if [ "$TARGET_GDBSERVER" ]; then
       log "Removing target gdbserver binary: $TARGET_GDBSERVER."
-      "$ADB" shell rm "$TARGET_GDBSERVER" >/dev/null 2>&1
+      "$ADB" shell "$COMMAND_PREFIX" rm "$TARGET_GDBSERVER" >/dev/null 2>&1
     fi
     log "Cleaning up: $TMPDIR"
     rm -rf "$TMPDIR"
@@ -96,6 +97,9 @@ NDK_DIR=
 NO_PULL_LIBS=
 PACKAGE_NAME=
 PID=
+PORT=
+PRIVILEGED=
+PRIVILEGED_INDEX=
 PROGRAM_NAME="activity"
 PULL_LIBS=
 PULL_LIBS_DIR=
@@ -143,6 +147,16 @@ for opt; do
       ;;
     --pid=*)
       PID=$optarg
+      ;;
+    --port=*)
+      PORT=$optarg
+      ;;
+    --privileged)
+      PRIVILEGED=true
+      ;;
+    --privileged=*)
+      PRIVILEGED=true
+      PRIVILEGED_INDEX=$optarg
       ;;
     --program-name=*)
       PROGRAM_NAME=$optarg
@@ -235,8 +249,9 @@ EOF
   cat <<EOF
 
 This script is used to debug a running $PROGRAM_NAME process.
-This can be a regular Android application process, or a sandboxed
-service, if you use the --sandboxed or --sandboxed=<num> option.
+This can be a regular Android application process, sandboxed (if you use the
+--sandboxed or --sandboxed=<num> option) or a privileged (--privileged or
+--privileged=<num>) service.
 
 This script needs several things to work properly. It will try to pick
 them up automatically for you though:
@@ -262,7 +277,7 @@ the CHROMIUM_OUT_DIR environment variable is defined.
 You can restrict this search by using --release or --debug to specify the
 build type, or simply use --symbol-dir=<path> to specify the file manually.
 
-The script tries to extract the target architecture from your GYP_DEFINES,
+The script tries to extract the target architecture from your target device,
 but if this fails, will default to 'arm'. Use --target-arch=<name> to force
 its value.
 
@@ -303,6 +318,8 @@ Valid options:
   --symbol-dir=<path>   Specify directory with symbol shared libraries.
   --out-dir=<path>      Specify the out directory.
   --package-name=<name> Specify package name (alternative to 1st argument).
+  --privileged          Debug first privileged process we find.
+  --privileged=<num>    Debug specific privileged process.
   --program-name=<name> Specify program name (cosmetic only).
   --pid=<pid>           Specify application process pid.
   --force               Kill any previous debugging session, if any.
@@ -316,6 +333,7 @@ Valid options:
   --gdb=<file>          Specify host gdb client binary.
   --target-arch=<name>  Specify NDK target arch.
   --adb=<file>          Specify host ADB binary.
+  --port=<port>         Specify the tcp port to use.
 
   --su-prefix=<prefix>  Prepend <prefix> to 'adb shell' commands that are
                         run by this script. This can be useful to use
@@ -338,7 +356,7 @@ if [ -z "$PACKAGE_NAME" ]; then
 fi
 
 if [ -z "$NDK_DIR" ]; then
-  ANDROID_NDK_ROOT=$(PYTHONPATH=build/android python -c \
+  ANDROID_NDK_ROOT=$(PYTHONPATH=$CHROMIUM_SRC/build/android python -c \
 'from pylib.constants import ANDROID_NDK_ROOT; print ANDROID_NDK_ROOT,')
 else
   if [ ! -d "$NDK_DIR" ]; then
@@ -354,15 +372,78 @@ if [ "$GDBINIT" -a ! -f "$GDBINIT" ]; then
   panic "Unknown --script file: $GDBINIT"
 fi
 
-# Find the target architecture from our $GYP_DEFINES
+# Check that ADB is in our path
+if [ -z "$ADB" ]; then
+  ADB=$(which adb 2>/dev/null)
+  if [ -z "$ADB" ]; then
+    panic "Can't find 'adb' tool in your path. Install it or use \
+--adb=<file>"
+  fi
+  log "Auto-config: --adb=$ADB"
+fi
+
+# Check that it works minimally
+ADB_VERSION=$($ADB version 2>/dev/null)
+echo "$ADB_VERSION" | fgrep -q -e "Android Debug Bridge"
+if [ $? != 0 ]; then
+  panic "Your 'adb' tool seems invalid, use --adb=<file> to specify a \
+different one: $ADB"
+fi
+
+# If there are more than one device connected, and ANDROID_SERIAL is not
+# defined, print an error message.
+NUM_DEVICES_PLUS2=$($ADB devices 2>/dev/null | wc -l)
+if [ "$NUM_DEVICES_PLUS2" -lt 3 -a -z "$ANDROID_SERIAL" ]; then
+  echo "ERROR: There is more than one Android device connected to ADB."
+  echo "Please define ANDROID_SERIAL to specify which one to use."
+  exit 1
+fi
+
+# Run a command through adb shell, strip the extra \r from the output
+# and return the correct status code to detect failures. This assumes
+# that the adb shell command prints a final \n to stdout.
+# $1+: command to run
+# Out: command's stdout
+# Return: command's status
+# Note: the command's stderr is lost
+adb_shell () {
+  local TMPOUT="$(mktemp)"
+  local LASTLINE RET
+  local ADB=${ADB:-adb}
+
+  # The weird sed rule is to strip the final \r on each output line
+  # Since 'adb shell' never returns the command's proper exit/status code,
+  # we force it to print it as '%%<status>' in the temporary output file,
+  # which we will later strip from it.
+  $ADB shell $@ ";" echo "%%\$?" 2>/dev/null | \
+      sed -e 's![[:cntrl:]]!!g' > $TMPOUT
+  # Get last line in log, which contains the exit code from the command
+  LASTLINE=$(sed -e '$!d' $TMPOUT)
+  # Extract the status code from the end of the line, which must
+  # be '%%<code>'.
+  RET=$(echo "$LASTLINE" | \
+    awk '{ if (match($0, "%%[0-9]+$")) { print substr($0,RSTART+2); } }')
+  # Remove the status code from the last line. Note that this may result
+  # in an empty line.
+  LASTLINE=$(echo "$LASTLINE" | \
+    awk '{ if (match($0, "%%[0-9]+$")) { print substr($0,1,RSTART-1); } }')
+  # The output itself: all lines except the status code.
+  sed -e '$d' $TMPOUT && printf "%s" "$LASTLINE"
+  # Remove temp file.
+  rm -f $TMPOUT
+  # Exit with the appropriate status.
+  return $RET
+}
+
+# Find the target architecture from the target device.
 # This returns an NDK-compatible architecture name.
 # out: NDK Architecture name, or empty string.
 get_gyp_target_arch () {
-  local ARCH=$(echo $GYP_DEFINES | tr ' ' '\n' | grep '^target_arch=' |\
-               cut -d= -f2)
+  local ARCH=$(adb_shell getprop ro.product.cpu.abi)
   case $ARCH in
-    ia32|i?86|x86) echo "x86";;
-    mips|arm|arm64|x86_64) echo "$ARCH";;
+    mips|x86|x86_64) echo "$ARCH";;
+    arm64*) echo "arm64";;
+    arm*) echo "arm";;
     *) echo "";
   esac
 }
@@ -579,35 +660,6 @@ valid one!"
   log "Auto-config: --gdbserver=$GDBSERVER"
 fi
 
-
-
-# Check that ADB is in our path
-if [ -z "$ADB" ]; then
-  ADB=$(which adb 2>/dev/null)
-  if [ -z "$ADB" ]; then
-    panic "Can't find 'adb' tool in your path. Install it or use \
---adb=<file>"
-  fi
-  log "Auto-config: --adb=$ADB"
-fi
-
-# Check that it works minimally
-ADB_VERSION=$($ADB version 2>/dev/null)
-echo "$ADB_VERSION" | fgrep -q -e "Android Debug Bridge"
-if [ $? != 0 ]; then
-  panic "Your 'adb' tool seems invalid, use --adb=<file> to specify a \
-different one: $ADB"
-fi
-
-# If there are more than one device connected, and ANDROID_SERIAL is not
-# defined, print an error message.
-NUM_DEVICES_PLUS2=$($ADB devices 2>/dev/null | wc -l)
-if [ "$NUM_DEVICES_PLUS2" -lt 3 -a -z "$ANDROID_SERIAL" ]; then
-  echo "ERROR: There is more than one Android device connected to ADB."
-  echo "Please define ANDROID_SERIAL to specify which one to use."
-  exit 1
-fi
-
 # A unique ID for this script's session. This needs to be the same in all
 # sub-shell commands we're going to launch, so take the PID of the launcher
 # process.
@@ -618,42 +670,6 @@ TMPDIR=/tmp/$USER-adb-gdb-tmp-$TMP_ID
 mkdir -p "$TMPDIR" && rm -rf "$TMPDIR"/*
 
 GDBSERVER_PIDFILE="$TMPDIR"/gdbserver-$TMP_ID.pid
-
-# Run a command through adb shell, strip the extra \r from the output
-# and return the correct status code to detect failures. This assumes
-# that the adb shell command prints a final \n to stdout.
-# $1+: command to run
-# Out: command's stdout
-# Return: command's status
-# Note: the command's stderr is lost
-adb_shell () {
-  local TMPOUT="$(mktemp)"
-  local LASTLINE RET
-  local ADB=${ADB:-adb}
-
-  # The weird sed rule is to strip the final \r on each output line
-  # Since 'adb shell' never returns the command's proper exit/status code,
-  # we force it to print it as '%%<status>' in the temporary output file,
-  # which we will later strip from it.
-  $ADB shell $@ ";" echo "%%\$?" 2>/dev/null | \
-      sed -e 's![[:cntrl:]]!!g' > $TMPOUT
-  # Get last line in log, which contains the exit code from the command
-  LASTLINE=$(sed -e '$!d' $TMPOUT)
-  # Extract the status code from the end of the line, which must
-  # be '%%<code>'.
-  RET=$(echo "$LASTLINE" | \
-    awk '{ if (match($0, "%%[0-9]+$")) { print substr($0,RSTART+2); } }')
-  # Remove the status code from the last line. Note that this may result
-  # in an empty line.
-  LASTLINE=$(echo "$LASTLINE" | \
-    awk '{ if (match($0, "%%[0-9]+$")) { print substr($0,1,RSTART-1); } }')
-  # The output itself: all lines except the status code.
-  sed -e '$d' $TMPOUT && printf "%s" "$LASTLINE"
-  # Remove temp file.
-  rm -f $TMPOUT
-  # Exit with the appropriate status.
-  return $RET
-}
 
 # If --force is specified, try to kill any gdbserver process started by the
 # same user on the device. Normally, these are killed automatically by the
@@ -736,7 +752,8 @@ if [ -z "$SYMBOL_DIR" ]; then
 fi
 
 # Allow several concurrent debugging sessions
-TARGET_GDBSERVER=/data/local/tmp/gdbserver-adb-gdb-$TMP_ID
+TARGET_GDBSERVER=/data/data/$PACKAGE_NAME/gdbserver-adb-gdb-$TMP_ID
+TMP_TARGET_GDBSERVER=/data/local/tmp/gdbserver-adb-gdb-$TMP_ID
 
 # Return the build fingerprint contained in a build.prop file.
 # $1: path to build.prop file
@@ -818,6 +835,12 @@ if [ -z "$PID" ]; then
     PROCESSNAME=$PROCESSNAME:sandboxed_process
     PID=$(adb_shell ps | \
           awk '$9 ~ /^'$PROCESSNAME'/ { print $2; }' | head -1)
+  elif [ "$PRIVILEGED_INDEX" ]; then
+    PROCESSNAME=$PROCESSNAME:privileged_process$PRIVILEGED_INDEX
+  elif [ "$PRIVILEGED" ]; then
+    PROCESSNAME=$PROCESSNAME:privileged_process
+    PID=$(adb_shell ps | \
+          awk '$9 ~ /^'$PROCESSNAME'/ { print $2; }' | head -1)
   fi
   if [ -z "$PID" ]; then
     PID=$(adb_shell ps | \
@@ -834,6 +857,8 @@ running? Try using --start."
   log "Found process PID: $PID"
 elif [ "$SANDBOXED" ]; then
   echo "WARNING: --sandboxed option ignored due to use of --pid."
+elif [ "$PRIVILEGED" ]; then
+  echo "WARNING: --privileged option ignored due to use of --pid."
 fi
 
 # Determine if 'adb shell' runs as root or not.
@@ -843,25 +868,29 @@ fi
 if [ "$SU_PREFIX" ]; then
   # Need to check that this works properly.
   SU_PREFIX_TEST_LOG=$TMPDIR/su-prefix.log
-  adb_shell $SU_PREFIX echo "foo" > $SU_PREFIX_TEST_LOG 2>&1
+  adb_shell $SU_PREFIX \"echo "foo"\" > $SU_PREFIX_TEST_LOG 2>&1
   if [ $? != 0 -o "$(cat $SU_PREFIX_TEST_LOG)" != "foo" ]; then
     echo "ERROR: Cannot use '$SU_PREFIX' as a valid su prefix:"
-    echo "$ adb shell $SU_PREFIX echo foo"
+    echo "$ adb shell $SU_PREFIX \"echo foo\""
     cat $SU_PREFIX_TEST_LOG
     exit 1
   fi
-  COMMAND_PREFIX="$SU_PREFIX"
+  COMMAND_PREFIX="$SU_PREFIX \""
+  COMMAND_SUFFIX="\""
 else
   SHELL_UID=$(adb shell cat /proc/self/status | \
               awk '$1 == "Uid:" { print $2; }')
   log "Shell UID: $SHELL_UID"
   if [ "$SHELL_UID" != 0 -o -n "$NO_ROOT" ]; then
     COMMAND_PREFIX="run-as $PACKAGE_NAME"
+    COMMAND_SUFFIX=
   else
     COMMAND_PREFIX=
+    COMMAND_SUFFIX=
   fi
 fi
 log "Command prefix: '$COMMAND_PREFIX'"
+log "Command suffix: '$COMMAND_SUFFIX'"
 
 # Pull device's system libraries that are mapped by our process.
 # Pulling all system libraries is too long, so determine which ones
@@ -869,7 +898,7 @@ log "Command prefix: '$COMMAND_PREFIX'"
 if [ "$PULL_LIBS" -a -z "$NO_PULL_LIBS" ]; then
   echo "Extracting system libraries into: $PULL_LIBS_DIR"
   rm -f $PULL_LIBS_DIR/build.prop
-  MAPPINGS=$(adb_shell $COMMAND_PREFIX cat /proc/$PID/maps)
+  MAPPINGS=$(adb_shell $COMMAND_PREFIX cat /proc/$PID/maps $COMMAND_SUFFIX)
   if [ $? != 0 ]; then
     echo "ERROR: Could not list process's memory mappings."
     if [ "$SU_PREFIX" ]; then
@@ -904,10 +933,14 @@ SOLIB_DIRS=$(find $PULL_LIBS_DIR -mindepth 1 -maxdepth 4 -type d | \
 
 # Push gdbserver to the device
 log "Pushing gdbserver $GDBSERVER to $TARGET_GDBSERVER"
-adb push $GDBSERVER $TARGET_GDBSERVER &>/dev/null
+adb push $GDBSERVER $TMP_TARGET_GDBSERVER &>/dev/null
+adb shell $COMMAND_PREFIX cp $TMP_TARGET_GDBSERVER $TARGET_GDBSERVER
+adb shell rm $TMP_TARGET_GDBSERVER
 fail_panic "Could not copy gdbserver to the device!"
 
-PORT=5039
+if [ -z "$PORT" ]; then
+    PORT=5039
+fi
 HOST_PORT=$PORT
 TARGET_PORT=$PORT
 
@@ -947,9 +980,9 @@ host:localhost:$HOST_PORT to device:localhost:$TARGET_PORT!"
 log "Starting gdbserver in the background:"
 GDBSERVER_LOG=$TMPDIR/gdbserver-$TMP_ID.log
 log "adb shell $COMMAND_PREFIX $TARGET_GDBSERVER :$TARGET_PORT \
---attach $PID"
+--attach $PID $COMMAND_SUFFIX"
 ("$ADB" shell $COMMAND_PREFIX $TARGET_GDBSERVER :$TARGET_PORT \
- --attach $PID > $GDBSERVER_LOG 2>&1) &
+ --attach $PID $COMMAND_SUFFIX > $GDBSERVER_LOG 2>&1) &
 GDBSERVER_PID=$!
 echo "$GDBSERVER_PID" > $GDBSERVER_PIDFILE
 log "background job pid: $GDBSERVER_PID"
